using System.Linq;
using Content.Client._ES.Auditions;
using Content.Client._ES.Core;
using Content.Client._ES.SecretIdentity;
using Content.Client._ES.Objectives;
using Content.Client._ES.Objectives.Ui;
using Content.Client.Mind;
using Content.Client.Roles;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Shared._ES.Auditions;
using Content.Shared._ES.Auditions.Components;
using Content.Shared._ES.SecretIdentity;
using Content.Shared._ES.Objectives.Components;
using Content.Shared._ES.SecretIdentity.Components;
using Content.Shared.Guidebook;
using Content.Shared.Localizations;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._ES.Mind.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESCharacterWindow : FancyWindow
{
    [Dependency] private IEntityManager _ent = default!;
    [Dependency] private IPlayerManager _player = default!;
    [Dependency] private IPrototypeManager _prototype = default!;
    private readonly GuidebookUIController _guidebook;
    private readonly ESAuditionsSystem _auditions;
    private readonly ESCluesSystem _clues;
    private readonly JobSystem _job;
    private readonly ESSecretIdentitySystem _secretIdentity;
    private readonly MindSystem _mind;
    private readonly ESObjectiveSystem _objective;
    private readonly SpriteSystem _sprite;

    public ESCharacterWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _guidebook = UserInterfaceManager.GetUIController<GuidebookUIController>();
        _auditions = _ent.System<ESAuditionsSystem>();
        _clues = _ent.System<ESCluesSystem>();
        _job = _ent.System<JobSystem>();
        _secretIdentity = _ent.System<ESSecretIdentitySystem>();
        _mind = _ent.System<MindSystem>();
        _objective = _ent.System<ESObjectiveSystem>();
        _sprite = _ent.System<SpriteSystem>();

        SecretIdentityHelpButton.OnPressed += OnSecretIdentityHelpPressed;
        ObjectiveHeaderLabel.UnsafeSetMarkup(Loc.GetString("es-character-window-objective-title"));
        Update();
    }

    protected override void Opened()
    {
        base.Opened();

        _secretIdentity.OnSecretIdentityChanged += OnSecretIdentityChanged;
        _secretIdentity.OnCharacterBlurbChanged += OnCharacterBlurbChanged;
        _objective.OnObjectivesChanged += OnObjectivesChanged;
    }

    public override void Close()
    {
        base.Close();

        _secretIdentity.OnSecretIdentityChanged -= OnSecretIdentityChanged;
        _secretIdentity.OnCharacterBlurbChanged -= OnCharacterBlurbChanged;
        _objective.OnObjectivesChanged -= OnObjectivesChanged;
    }

    private void OnSecretIdentityChanged(EntityUid mind, ProtoId<ESSecretIdentityPrototype>? secretIdentity)
    {
        if (_player.LocalUser is null)
            return;

        if (mind != _mind.GetMind(_player.LocalUser.Value))
            return;

        Update();
    }

    private void OnCharacterBlurbChanged(Entity<ESCharacterBlurbComponent> mind)
    {
        if (_player.LocalUser is null)
            return;

        if (mind != _mind.GetMind(_player.LocalUser.Value))
            return;

        Update();
    }

    private void OnObjectivesChanged(Entity<ESObjectiveHolderComponent> holder)
    {
        if (_player.LocalUser is null)
            return;

        if (holder != _mind.GetMind(_player.LocalUser.Value))
            return;

        Update();
    }

    private void OnSecretIdentityHelpPressed(BaseButton.ButtonEventArgs? args)
    {
        if (_player.LocalEntity is not { } localEntity)
            return;

        if (!_mind.TryGetMind(localEntity, out var mind, out var mindComp))
            return;

        // if theres a guide entry with the same id as the secret identity then open that
        // with the organization guide as the root
        if (_secretIdentity.TryGetSecretIdentity((mind, mindComp), out var secretIdentityId)
            && _prototype.Index(secretIdentityId.Value) is { } secretIdentity
            && _prototype.HasIndex<GuideEntryPrototype>(secretIdentity.ID))
        {
            _guidebook.OpenGuidebook(selected: secretIdentity.ID);
        }
    }

    public void Update()
    {
        // Oh no!
        if (_player.LocalEntity is not { } localEntity)
            return;

        SelfView.SetEntity(localEntity);

        if (!_mind.TryGetMind(localEntity, out var mind, out var mindComp))
            return;

        if (_ent.TryGetComponent<ESCharacterComponent>(mind, out var character))
        {
            NameLabel.UnsafeSetMarkup(Loc.GetString("es-character-window-name-fmt", ("name", character.Name)));
            PromptLabel.UnsafeSetMarkup(_auditions.GetCharacterPrompt((mind, character)));
            CharacterInfoLabel.UnsafeSetMarkup(Loc.GetString("es-character-info-blurb",
                ("gender", _clues.SexToString(character.Profile.Sex)),
                ("age", character.Profile.Age),
                ("day", character.DateOfBirth.Day),
                ("month", Loc.GetString($"month-{character.DateOfBirth.Month}"))));
            LikesLabel.UnsafeSetMarkup(Loc.GetString("es-character-personality-likes",
                ("things", ContentLocalizationManager.FormatList(character.Likes.Select(e => Loc.GetString(e)).ToList()))));
            DislikesLabel.UnsafeSetMarkup(Loc.GetString("es-character-personality-dislikes",
                ("things", ContentLocalizationManager.FormatList(character.Dislikes.Select(e => Loc.GetString(e)).ToList()))));
        }

        if (_job.MindTryGetJob(mind, out var job))
        {
            JobLabel.UnsafeSetMarkup(Loc.GetString("es-character-window-job-fmt", ("name", job.LocalizedName)));
            JobIconTexture.Texture = _sprite.Frame0(_prototype.Index(job.Icon).Icon);
        }

        if (_secretIdentity.TryGetSecretIdentity((mind, mindComp), out var secretIdentityId))
        {
            var secretIdentity = _prototype.Index(secretIdentityId);
            var organization = _prototype.Index(secretIdentity.Organization);

            var modifierName = "null";
            var modifierColor = Color.White;
            if (_secretIdentity.TryGetSecretIdentityModifier((mind, mindComp), out var modifierId))
            {
                var modifier = _prototype.Index(modifierId);

                modifierName = Loc.GetString(modifier.Name);
                modifierColor = modifier.Color;
            }

            SecretIdentityLabel.UnsafeSetMarkup(Loc.GetString("es-character-window-secret-identity-fmt",
                ("name", Loc.GetString(secretIdentity.Name)),
                ("color", secretIdentity.Color),
                ("modifierName", modifierName),
                ("modifierColor", modifierColor)));

            OrganizationLabel.UnsafeSetMarkup(Loc.GetString("es-character-window-organization-fmt",
                ("name", Loc.GetString(organization.Name)),
                ("color", organization.Color)));

            SecretIdentityHelpButton.Visible = true;
        }
        else
        {
            SecretIdentityLabel.UnsafeSetMarkup(Loc.GetString("es-character-window-secret-identity-fmt",
                ("name", Loc.GetString("generic-unknown-title")),
                ("color", Color.White),
                ("modifierName", string.Empty),
                ("modifierColor", Color.White)));

            OrganizationLabel.UnsafeSetMarkup(Loc.GetString("es-character-window-organization-fmt",
                ("name", Loc.GetString("generic-unknown-title")),
                ("color", Color.Gray)));

            SecretIdentityHelpButton.Visible = false;
        }

        var info = _secretIdentity.GetCharacterInfoBlurb(mind);
        var formattedMsg = new FormattedMessage();
        foreach (var msg in info)
        {
            if (info.IndexOf(msg) != 0)
                formattedMsg.PushNewline();
            formattedMsg.AddMessage(msg);
            formattedMsg.PushNewline();
        }
        InfoBlurbText.SetMessage(formattedMsg);
        InfoBlurbText.Visible = !formattedMsg.IsEmpty;

        ObjectivesContainer.Children.Clear();
        foreach (var objective in _objective.GetObjectives(mind))
        {
            var control = new ESObjectiveControl();
            control.SetObjective(objective);
            ObjectivesContainer.AddChild(control);
        }
    }
}
