- type: esSecretIdentity
  id: ESBaseCommandRestricted
  abstract: true
  prohibitedJobs:
  - ESCaptain
  - ESStationAdmin

- type: esSecretIdentity
  id: ESBaseCommandSecRestricted
  abstract: true
  prohibitedJobs:
  # Command
  - ESCaptain
  - ESStationAdmin
  # Security
  - ESSecurityOfficer
  - ESDetective

- type: esSecretIdentity
  id: ESBaseCrew
  organization: Crew
  abstract: true
  modifierChance: 0.066
  modifiers:
    ExSyndicate: 1

- type: esSecretIdentity
  parent: ESBaseCommandRestricted
  id: ESBaseParasite
  organization: Parasite
  abstract: true
  components:
  - type: ESOrganizationFactionIcon
    icon: ESParasite
    organization: Parasite
    examineString: es-secret-identity-organization-parasite-examine
  mindComponents: # Goes on the mind so that we don't overwrite the base component on the mob
  - type: ESChatPermissions
    inherentChannels:
    - ParasiteHivemind
  objectives:
    all:
    - id: ESObjectiveParasiteDie
    - id: ESObjectiveParasiteDoNotKill

- type: esSecretIdentity
  parent: ESBaseCommandRestricted
  id: ESBaseTraitor
  organization: Traitor
  abstract: true
  actions:
    all:
    - id: ESActionSyndieTransponder
  components:
  - type: ESOrganizationFactionIcon
    icon: ESTraitor
    organization: Traitor
    examineString: es-secret-identity-organization-traitor-examine

- type: entity
  parent: BaseMentalAction
  id: ESActionSyndieTransponder
  name: Syndicate Transponder
  description: Allows you to covertly relay information to your fellow traitors.
  components:
  - type: Action
    icon:
      sprite: Objects/Devices/communication.rsi
      state: old-radio
    useDelay: 210
  - type: InstantAction
    event: !type:ESTransponderActionEvent
      channel: SyndicateTransponder
